=begin
#OpenLattice API

#OpenLattice API

The version of the OpenAPI document: 0.0.1
Contact: support@openlattice.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class IntegrationStatus
    IN_PROGRESS = "IN_PROGRESS".freeze
    SUCCEEDED = "SUCCEEDED".freeze
    FAILED = "FAILED".freeze
    QUEUED = "QUEUED".freeze
    FAILED_TO_START = "FAILED_TO_START".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = IntegrationStatus.constants.select { |c| IntegrationStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #IntegrationStatus" if constantValues.empty?
      value
    end
  end
end
