/**
 * OpenLattice API
 * OpenLattice API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.EntityType;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AssociationType {
  
  @SerializedName("entityType")
  private EntityType entityType = null;
  @SerializedName("src")
  private List<String> src = null;
  @SerializedName("dst")
  private List<String> dst = null;
  @SerializedName("bidirectional")
  private Boolean bidirectional = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public EntityType getEntityType() {
    return entityType;
  }
  public void setEntityType(EntityType entityType) {
    this.entityType = entityType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getSrc() {
    return src;
  }
  public void setSrc(List<String> src) {
    this.src = src;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getDst() {
    return dst;
  }
  public void setDst(List<String> dst) {
    this.dst = dst;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getBidirectional() {
    return bidirectional;
  }
  public void setBidirectional(Boolean bidirectional) {
    this.bidirectional = bidirectional;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssociationType associationType = (AssociationType) o;
    return (this.entityType == null ? associationType.entityType == null : this.entityType.equals(associationType.entityType)) &&
        (this.src == null ? associationType.src == null : this.src.equals(associationType.src)) &&
        (this.dst == null ? associationType.dst == null : this.dst.equals(associationType.dst)) &&
        (this.bidirectional == null ? associationType.bidirectional == null : this.bidirectional.equals(associationType.bidirectional));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.entityType == null ? 0: this.entityType.hashCode());
    result = 31 * result + (this.src == null ? 0: this.src.hashCode());
    result = 31 * result + (this.dst == null ? 0: this.dst.hashCode());
    result = 31 * result + (this.bidirectional == null ? 0: this.bidirectional.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssociationType {\n");
    
    sb.append("  entityType: ").append(entityType).append("\n");
    sb.append("  src: ").append(src).append("\n");
    sb.append("  dst: ").append(dst).append("\n");
    sb.append("  bidirectional: ").append(bidirectional).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
