/**
 * OpenLattice API
 * OpenLattice API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Map;
import org.openapitools.client.model.EntitySet;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class NeighborEntityDetails {
  
  @SerializedName("associationEntitySet")
  private EntitySet associationEntitySet = null;
  @SerializedName("associationDetails")
  private Map<String, List<String>> associationDetails = null;
  @SerializedName("neighborEntitySet")
  private EntitySet neighborEntitySet = null;
  @SerializedName("neighborId")
  private String neighborId = null;
  @SerializedName("neighborDetails")
  private Map<String, List<String>> neighborDetails = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public EntitySet getAssociationEntitySet() {
    return associationEntitySet;
  }
  public void setAssociationEntitySet(EntitySet associationEntitySet) {
    this.associationEntitySet = associationEntitySet;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, List<String>> getAssociationDetails() {
    return associationDetails;
  }
  public void setAssociationDetails(Map<String, List<String>> associationDetails) {
    this.associationDetails = associationDetails;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public EntitySet getNeighborEntitySet() {
    return neighborEntitySet;
  }
  public void setNeighborEntitySet(EntitySet neighborEntitySet) {
    this.neighborEntitySet = neighborEntitySet;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNeighborId() {
    return neighborId;
  }
  public void setNeighborId(String neighborId) {
    this.neighborId = neighborId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, List<String>> getNeighborDetails() {
    return neighborDetails;
  }
  public void setNeighborDetails(Map<String, List<String>> neighborDetails) {
    this.neighborDetails = neighborDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NeighborEntityDetails neighborEntityDetails = (NeighborEntityDetails) o;
    return (this.associationEntitySet == null ? neighborEntityDetails.associationEntitySet == null : this.associationEntitySet.equals(neighborEntityDetails.associationEntitySet)) &&
        (this.associationDetails == null ? neighborEntityDetails.associationDetails == null : this.associationDetails.equals(neighborEntityDetails.associationDetails)) &&
        (this.neighborEntitySet == null ? neighborEntityDetails.neighborEntitySet == null : this.neighborEntitySet.equals(neighborEntityDetails.neighborEntitySet)) &&
        (this.neighborId == null ? neighborEntityDetails.neighborId == null : this.neighborId.equals(neighborEntityDetails.neighborId)) &&
        (this.neighborDetails == null ? neighborEntityDetails.neighborDetails == null : this.neighborDetails.equals(neighborEntityDetails.neighborDetails));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.associationEntitySet == null ? 0: this.associationEntitySet.hashCode());
    result = 31 * result + (this.associationDetails == null ? 0: this.associationDetails.hashCode());
    result = 31 * result + (this.neighborEntitySet == null ? 0: this.neighborEntitySet.hashCode());
    result = 31 * result + (this.neighborId == null ? 0: this.neighborId.hashCode());
    result = 31 * result + (this.neighborDetails == null ? 0: this.neighborDetails.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class NeighborEntityDetails {\n");
    
    sb.append("  associationEntitySet: ").append(associationEntitySet).append("\n");
    sb.append("  associationDetails: ").append(associationDetails).append("\n");
    sb.append("  neighborEntitySet: ").append(neighborEntitySet).append("\n");
    sb.append("  neighborId: ").append(neighborId).append("\n");
    sb.append("  neighborDetails: ").append(neighborDetails).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
