/**
 * OpenLattice API
 * OpenLattice API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.FullQualifiedName;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PropertyDefinition {
  
  @SerializedName("type")
  private FullQualifiedName type = null;
  @SerializedName("column")
  private String column = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public FullQualifiedName getType() {
    return type;
  }
  public void setType(FullQualifiedName type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getColumn() {
    return column;
  }
  public void setColumn(String column) {
    this.column = column;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyDefinition propertyDefinition = (PropertyDefinition) o;
    return (this.type == null ? propertyDefinition.type == null : this.type.equals(propertyDefinition.type)) &&
        (this.column == null ? propertyDefinition.column == null : this.column.equals(propertyDefinition.column));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.column == null ? 0: this.column.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyDefinition {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  column: ").append(column).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
