# coding: utf-8

"""
    OpenLattice API

    OpenLattice API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@openlattice.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openlattice
from openlattice.models.entity_type import EntityType  # noqa: E501
from openlattice.rest import ApiException

class TestEntityType(unittest.TestCase):
    """EntityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EntityType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openlattice.models.entity_type.EntityType()  # noqa: E501
        if include_optional :
            return EntityType(
                title = '0', 
                description = '0', 
                id = '0', 
                type = openlattice.models.full_qualified_name.FullQualifiedName(
                    name = '0', 
                    namespace = '0', ), 
                schemas = [
                    openlattice.models.full_qualified_name.FullQualifiedName(
                        name = '0', 
                        namespace = '0', )
                    ], 
                key = [
                    '0'
                    ], 
                properties = [
                    '0'
                    ], 
                property_tags = {
                    'key' : [
                        '0'
                        ]
                    }, 
                basetype = '0', 
                category = 'AssociationType'
            )
        else :
            return EntityType(
        )

    def testEntityType(self):
        """Test EntityType"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
