# coding: utf-8

"""
    OpenLattice API

    OpenLattice API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@openlattice.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openlattice
from openlattice.api.app_api import AppApi  # noqa: E501
from openlattice.rest import ApiException


class TestAppApi(unittest.TestCase):
    """AppApi unit test stubs"""

    def setUp(self):
        self.api = openlattice.api.app_api.AppApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_app(self):
        """Test case for create_app

        Create an app if it doesn't exist.  # noqa: E501
        """
        pass

    def test_create_app_role(self):
        """Test case for create_app_role

        Create an app role  # noqa: E501
        """
        pass

    def test_delete_app(self):
        """Test case for delete_app

        Delete an app  # noqa: E501
        """
        pass

    def test_delete_role_from_app(self):
        """Test case for delete_role_from_app

        Delete an app role  # noqa: E501
        """
        pass

    def test_get_app(self):
        """Test case for get_app

        Get an app based on the ID  # noqa: E501
        """
        pass

    def test_get_app_by_name(self):
        """Test case for get_app_by_name

        Get an app based on the name  # noqa: E501
        """
        pass

    def test_get_apps(self):
        """Test case for get_apps

        Get all apps  # noqa: E501
        """
        pass

    def test_get_available_app_configs(self):
        """Test case for get_available_app_configs

        Get available app configurations  # noqa: E501
        """
        pass

    def test_get_available_app_configs_old(self):
        """Test case for get_available_app_configs_old

        Get historical app configurations for an app  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
