# coding: utf-8

"""
    OpenLattice API

    OpenLattice API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@openlattice.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openlattice
from openlattice.api.shuttle_api import ShuttleApi  # noqa: E501
from openlattice.rest import ApiException


class TestShuttleApi(unittest.TestCase):
    """ShuttleApi unit test stubs"""

    def setUp(self):
        self.api = openlattice.api.shuttle_api.ShuttleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_integration_definition(self):
        """Test case for create_integration_definition

        Creates a new integration definition for running recurring integrations  # noqa: E501
        """
        pass

    def test_delete_integration_definition(self):
        """Test case for delete_integration_definition

        Replaces any number of fields within an existing integration definition  # noqa: E501
        """
        pass

    def test_delete_integration_job_status(self):
        """Test case for delete_integration_job_status

        Deletes an integration job status from the integrationJobs map  # noqa: E501
        """
        pass

    def test_enqueue_integration(self):
        """Test case for enqueue_integration

        Enqueues an integration on Shuttle Server for a given integration  # noqa: E501
        """
        pass

    def test_poll_all_integrations(self):
        """Test case for poll_all_integrations

        Polls the statuses of all running integrations  # noqa: E501
        """
        pass

    def test_poll_integration(self):
        """Test case for poll_integration

        Polls the status of an integration  # noqa: E501
        """
        pass

    def test_read_integration_definition(self):
        """Test case for read_integration_definition

        Gets an existing integration definition  # noqa: E501
        """
        pass

    def test_update_integration_definition(self):
        """Test case for update_integration_definition

        Replaces any number of fields within an existing integration definition  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
