# coding: utf-8

"""
    OpenLattice API

    OpenLattice API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@openlattice.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openlattice
from openlattice.models.ace import Ace  # noqa: E501
from openlattice.rest import ApiException

class TestAce(unittest.TestCase):
    """Ace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Ace
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openlattice.models.ace.Ace()  # noqa: E501
        if include_optional :
            return Ace(
                principal = openlattice.models.principal.Principal(
                    type = '0', 
                    id = '0', ), 
                permissions = [
                    '0'
                    ]
            )
        else :
            return Ace(
        )

    def testAce(self):
        """Test Ace"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
