# coding: utf-8

"""
    OpenLattice API

    OpenLattice API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@openlattice.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openlattice
from openlattice.models.data_edge import DataEdge  # noqa: E501
from openlattice.rest import ApiException


class TestDataEdge(unittest.TestCase):
    """DataEdge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataEdge(self):
        """Test DataEdge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openlattice.models.data_edge.DataEdge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
