/**
 * OpenLattice API
 * OpenLattice API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenLatticeApi);
  }
}(this, function(expect, OpenLatticeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenLatticeApi.AssemblyAggregationFilter();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssemblyAggregationFilter', function() {
    it('should create an instance of AssemblyAggregationFilter', function() {
      // uncomment below and update the code to test AssemblyAggregationFilter
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be.a(OpenLatticeApi.AssemblyAggregationFilter);
    });

    it('should have the property organizationId (base name: "organizationId")', function() {
      // uncomment below and update the code to test the property organizationId
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be();
    });

    it('should have the property srcEntitySetId (base name: "srcEntitySetId")', function() {
      // uncomment below and update the code to test the property srcEntitySetId
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be();
    });

    it('should have the property edgeEntitySetId (base name: "edgeEntitySetId")', function() {
      // uncomment below and update the code to test the property edgeEntitySetId
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be();
    });

    it('should have the property dstEntitySetId (base name: "dstEntitySetId")', function() {
      // uncomment below and update the code to test the property dstEntitySetId
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be();
    });

    it('should have the property groupings (base name: "groupings")', function() {
      // uncomment below and update the code to test the property groupings
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be();
    });

    it('should have the property aggregations (base name: "aggregations")', function() {
      // uncomment below and update the code to test the property aggregations
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be();
    });

    it('should have the property calculations (base name: "calculations")', function() {
      // uncomment below and update the code to test the property calculations
      //var instane = new OpenLatticeApi.AssemblyAggregationFilter();
      //expect(instance).to.be();
    });

  });

}));
