/**
 * OpenLattice API
 * OpenLattice API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenLatticeApi);
  }
}(this, function(expect, OpenLatticeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenLatticeApi.LinkingFeedback();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LinkingFeedback', function() {
    it('should create an instance of LinkingFeedback', function() {
      // uncomment below and update the code to test LinkingFeedback
      //var instane = new OpenLatticeApi.LinkingFeedback();
      //expect(instance).to.be.a(OpenLatticeApi.LinkingFeedback);
    });

    it('should have the property linkingEntity (base name: "linkingEntity")', function() {
      // uncomment below and update the code to test the property linkingEntity
      //var instane = new OpenLatticeApi.LinkingFeedback();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instane = new OpenLatticeApi.LinkingFeedback();
      //expect(instance).to.be();
    });

    it('should have the property unlink (base name: "unlink")', function() {
      // uncomment below and update the code to test the property unlink
      //var instane = new OpenLatticeApi.LinkingFeedback();
      //expect(instance).to.be();
    });

  });

}));
