# OpenLattice API
#
# OpenLattice API
#
# OpenAPI spec version: 0.0.1
# Contact: support@openlattice.com
# Generated by: https://openapi-generator.tech

#' @title Authorizations operations
#' @description openlattice.Authorizations
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' check_authorizations Check authorizations
#'
#'
#' get_accessible_objects Returns paged results for all authorized objects of specified objectType, that the current user has specified permission for.
#'
#' }
#'
#' @export
AuthorizationsApi <- R6::R6Class(
  'AuthorizationsApi',
  public = list(
    userAgent = "OpenAPI-Generator/0.1/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    check_authorizations = function(access_check, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`access_check`)) {
        body <- `access_check`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/datastore/authorizations"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
                jsonlite::fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_accessible_objects = function(object_type, permission, paging_token, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`object_type`)) {
        queryParams['objectType'] <- object_type
      }

      if (!missing(`permission`)) {
        queryParams['permission'] <- permission
      }

      if (!missing(`paging_token`)) {
        queryParams['pagingToken'] <- paging_token
      }

      urlPath <- "/datastore/authorizations"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
                jsonlite::fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
