# OpenLattice API
#
# OpenLattice API
#
# OpenAPI spec version: 0.0.1
# Contact: support@openlattice.com
# Generated by: https://openapi-generator.tech


#' DataAssociation Class
#'
#' @field srcEntitySetId 
#' @field srcEntityIndex 
#' @field srcEntityKeyId 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataAssociation <- R6::R6Class(
  'DataAssociation',
  public = list(
    `srcEntitySetId` = NULL,
    `srcEntityIndex` = NULL,
    `srcEntityKeyId` = NULL,
    initialize = function(`srcEntitySetId`, `srcEntityIndex`, `srcEntityKeyId`){
      if (!missing(`srcEntitySetId`)) {
                stopifnot(is.character(`srcEntitySetId`), length(`srcEntitySetId`) == 1)
        self$`srcEntitySetId` <- `srcEntitySetId`
      }
      if (!missing(`srcEntityIndex`)) {
                stopifnot(is.character(`srcEntityIndex`), length(`srcEntityIndex`) == 1)
        self$`srcEntityIndex` <- `srcEntityIndex`
      }
      if (!missing(`srcEntityKeyId`)) {
                stopifnot(is.character(`srcEntityKeyId`), length(`srcEntityKeyId`) == 1)
        self$`srcEntityKeyId` <- `srcEntityKeyId`
      }
    },
    toJSON = function() {
      DataAssociationObject <- list()
      if (!is.null(self$`srcEntitySetId`)) {
        DataAssociationObject[['srcEntitySetId']] <-
                self$`srcEntitySetId`
      }
      if (!is.null(self$`srcEntityIndex`)) {
        DataAssociationObject[['srcEntityIndex']] <-
                self$`srcEntityIndex`
      }
      if (!is.null(self$`srcEntityKeyId`)) {
        DataAssociationObject[['srcEntityKeyId']] <-
                self$`srcEntityKeyId`
      }

      DataAssociationObject
    },
    fromJSON = function(DataAssociationJson) {
      DataAssociationObject <- jsonlite::fromJSON(DataAssociationJson)
      if (!is.null(DataAssociationObject$`srcEntitySetId`)) {
                self$`srcEntitySetId` <- DataAssociationObject$`srcEntitySetId`
      }
      if (!is.null(DataAssociationObject$`srcEntityIndex`)) {
                self$`srcEntityIndex` <- DataAssociationObject$`srcEntityIndex`
      }
      if (!is.null(DataAssociationObject$`srcEntityKeyId`)) {
                self$`srcEntityKeyId` <- DataAssociationObject$`srcEntityKeyId`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "srcEntitySetId":
                      
                      "%s"
                  
              ,
           "srcEntityIndex":
                      
                      "%s"
                  
              ,
           "srcEntityKeyId":
                      
                      "%s"
                  
              
        }',
                self$`srcEntitySetId`,
                self$`srcEntityIndex`,
                self$`srcEntityKeyId`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(DataAssociationJson) {
      DataAssociationObject <- jsonlite::fromJSON(DataAssociationJson)
              self$`srcEntitySetId` <- DataAssociationObject$`srcEntitySetId`
              self$`srcEntityIndex` <- DataAssociationObject$`srcEntityIndex`
              self$`srcEntityKeyId` <- DataAssociationObject$`srcEntityKeyId`
    }
  )
)
