# OpenLattice API
#
# OpenLattice API
#
# OpenAPI spec version: 0.0.1
# Contact: support@openlattice.com
# Generated by: https://openapi-generator.tech


#' EntitySetCollection Class
#'
#' @field id 
#' @field name 
#' @field title 
#' @field description 
#' @field entityTypeCollectionId 
#' @field template 
#' @field contacts 
#' @field organizationId 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntitySetCollection <- R6::R6Class(
  'EntitySetCollection',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `title` = NULL,
    `description` = NULL,
    `entityTypeCollectionId` = NULL,
    `template` = NULL,
    `contacts` = NULL,
    `organizationId` = NULL,
    initialize = function(`id`, `name`, `title`, `description`, `entityTypeCollectionId`, `template`, `contacts`, `organizationId`){
      if (!missing(`id`)) {
                stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
                stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`title`)) {
                stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`description`)) {
                stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`entityTypeCollectionId`)) {
                stopifnot(is.character(`entityTypeCollectionId`), length(`entityTypeCollectionId`) == 1)
        self$`entityTypeCollectionId` <- `entityTypeCollectionId`
      }
      if (!missing(`template`)) {
        self$`template` <- `template`
      }
      if (!missing(`contacts`)) {
                stopifnot(is.vector(`contacts`), length(`contacts`) != 0)
                sapply(`contacts`, function(x) stopifnot(is.character(x)))
        self$`contacts` <- `contacts`
      }
      if (!missing(`organizationId`)) {
                stopifnot(is.character(`organizationId`), length(`organizationId`) == 1)
        self$`organizationId` <- `organizationId`
      }
    },
    toJSON = function() {
      EntitySetCollectionObject <- list()
      if (!is.null(self$`id`)) {
        EntitySetCollectionObject[['id']] <-
                self$`id`
      }
      if (!is.null(self$`name`)) {
        EntitySetCollectionObject[['name']] <-
                self$`name`
      }
      if (!is.null(self$`title`)) {
        EntitySetCollectionObject[['title']] <-
                self$`title`
      }
      if (!is.null(self$`description`)) {
        EntitySetCollectionObject[['description']] <-
                self$`description`
      }
      if (!is.null(self$`entityTypeCollectionId`)) {
        EntitySetCollectionObject[['entityTypeCollectionId']] <-
                self$`entityTypeCollectionId`
      }
      if (!is.null(self$`template`)) {
        EntitySetCollectionObject[['template']] <-
                self$`template`
      }
      if (!is.null(self$`contacts`)) {
        EntitySetCollectionObject[['contacts']] <-
                self$`contacts`
      }
      if (!is.null(self$`organizationId`)) {
        EntitySetCollectionObject[['organizationId']] <-
                self$`organizationId`
      }

      EntitySetCollectionObject
    },
    fromJSON = function(EntitySetCollectionJson) {
      EntitySetCollectionObject <- jsonlite::fromJSON(EntitySetCollectionJson)
      if (!is.null(EntitySetCollectionObject$`id`)) {
                self$`id` <- EntitySetCollectionObject$`id`
      }
      if (!is.null(EntitySetCollectionObject$`name`)) {
                self$`name` <- EntitySetCollectionObject$`name`
      }
      if (!is.null(EntitySetCollectionObject$`title`)) {
                self$`title` <- EntitySetCollectionObject$`title`
      }
      if (!is.null(EntitySetCollectionObject$`description`)) {
                self$`description` <- EntitySetCollectionObject$`description`
      }
      if (!is.null(EntitySetCollectionObject$`entityTypeCollectionId`)) {
                self$`entityTypeCollectionId` <- EntitySetCollectionObject$`entityTypeCollectionId`
      }
      if (!is.null(EntitySetCollectionObject$`template`)) {
                self$`template` <- EntitySetCollectionObject$`template`
      }
      if (!is.null(EntitySetCollectionObject$`contacts`)) {
                self$`contacts` <- EntitySetCollectionObject$`contacts`
      }
      if (!is.null(EntitySetCollectionObject$`organizationId`)) {
                self$`organizationId` <- EntitySetCollectionObject$`organizationId`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "id":
                      
                      "%s"
                  
              ,
           "name":
                      
                      "%s"
                  
              ,
           "title":
                      
                      "%s"
                  
              ,
           "description":
                      
                      "%s"
                  
              ,
           "entityTypeCollectionId":
                      
                      "%s"
                  
              ,
           "template":
                      
                      "%s"
                  
              ,
           "contacts":
                      
                      ["%s"]
                  
              ,
           "organizationId":
                      
                      "%s"
                  
              
        }',
                self$`id`,
                self$`name`,
                self$`title`,
                self$`description`,
                self$`entityTypeCollectionId`,
                self$`template`,
                paste0(self$`contacts`, collapse='","'),
                self$`organizationId`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(EntitySetCollectionJson) {
      EntitySetCollectionObject <- jsonlite::fromJSON(EntitySetCollectionJson)
              self$`id` <- EntitySetCollectionObject$`id`
              self$`name` <- EntitySetCollectionObject$`name`
              self$`title` <- EntitySetCollectionObject$`title`
              self$`description` <- EntitySetCollectionObject$`description`
              self$`entityTypeCollectionId` <- EntitySetCollectionObject$`entityTypeCollectionId`
              self$`template` <- EntitySetCollectionObject$`template`
              self$`contacts` <- EntitySetCollectionObject$`contacts`
              self$`organizationId` <- EntitySetCollectionObject$`organizationId`
    }
  )
)
