# OpenLattice API
#
# OpenLattice API
#
# The version of the OpenAPI document: 0.0.1
# Contact: support@openlattice.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EntityKey
#' @description EntityKey Class
#' @format An \code{R6Class} generator object
#' @field entitySetId  character [optional]
#'
#' @field entityId  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntityKey <- R6::R6Class(
  'EntityKey',
  public = list(
    `entitySetId` = NULL,
    `entityId` = NULL,
    initialize = function(`entitySetId`=NULL, `entityId`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`entitySetId`)) {
        stopifnot(is.character(`entitySetId`), length(`entitySetId`) == 1)
        self$`entitySetId` <- `entitySetId`
      }
      if (!is.null(`entityId`)) {
        stopifnot(is.character(`entityId`), length(`entityId`) == 1)
        self$`entityId` <- `entityId`
      }
    },
    toJSON = function() {
      EntityKeyObject <- list()
      if (!is.null(self$`entitySetId`)) {
        EntityKeyObject[['entitySetId']] <-
          self$`entitySetId`
      }
      if (!is.null(self$`entityId`)) {
        EntityKeyObject[['entityId']] <-
          self$`entityId`
      }

      EntityKeyObject
    },
    fromJSON = function(EntityKeyJson) {
      EntityKeyObject <- jsonlite::fromJSON(EntityKeyJson)
      if (!is.null(EntityKeyObject$`entitySetId`)) {
        self$`entitySetId` <- EntityKeyObject$`entitySetId`
      }
      if (!is.null(EntityKeyObject$`entityId`)) {
        self$`entityId` <- EntityKeyObject$`entityId`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entitySetId`)) {
        sprintf(
        '"entitySetId":
          "%s"
                ',
        self$`entitySetId`
        )},
        if (!is.null(self$`entityId`)) {
        sprintf(
        '"entityId":
          "%s"
                ',
        self$`entityId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EntityKeyJson) {
      EntityKeyObject <- jsonlite::fromJSON(EntityKeyJson)
      self$`entitySetId` <- EntityKeyObject$`entitySetId`
      self$`entityId` <- EntityKeyObject$`entityId`
      self
    }
  )
)
