# OpenLattice API
#
# OpenLattice API
#
# OpenAPI spec version: 0.0.1
# Contact: support@openlattice.com
# Generated by: https://openapi-generator.tech


#' FullQualifiedName Class
#'
#' @field name 
#' @field namespace 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FullQualifiedName <- R6::R6Class(
  'FullQualifiedName',
  public = list(
    `name` = NULL,
    `namespace` = NULL,
    initialize = function(`name`, `namespace`){
      if (!missing(`name`)) {
                stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`namespace`)) {
                stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
    },
    toJSON = function() {
      FullQualifiedNameObject <- list()
      if (!is.null(self$`name`)) {
        FullQualifiedNameObject[['name']] <-
                self$`name`
      }
      if (!is.null(self$`namespace`)) {
        FullQualifiedNameObject[['namespace']] <-
                self$`namespace`
      }

      FullQualifiedNameObject
    },
    fromJSON = function(FullQualifiedNameJson) {
      FullQualifiedNameObject <- jsonlite::fromJSON(FullQualifiedNameJson)
      if (!is.null(FullQualifiedNameObject$`name`)) {
                self$`name` <- FullQualifiedNameObject$`name`
      }
      if (!is.null(FullQualifiedNameObject$`namespace`)) {
                self$`namespace` <- FullQualifiedNameObject$`namespace`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "name":
                      
                      "%s"
                  
              ,
           "namespace":
                      
                      "%s"
                  
              
        }',
                self$`name`,
                self$`namespace`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(FullQualifiedNameJson) {
      FullQualifiedNameObject <- jsonlite::fromJSON(FullQualifiedNameJson)
              self$`name` <- FullQualifiedNameObject$`name`
              self$`namespace` <- FullQualifiedNameObject$`namespace`
    }
  )
)
