# OpenLattice API
#
# OpenLattice API
#
# OpenAPI spec version: 0.0.1
# Contact: support@openlattice.com
# Generated by: https://openapi-generator.tech


#' IndexingState Class
#'
#' @field indexing 
#' @field queue 
#' @field currentEntitySet 
#' @field queueSize 
#' @field count 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IndexingState <- R6::R6Class(
  'IndexingState',
  public = list(
    `indexing` = NULL,
    `queue` = NULL,
    `currentEntitySet` = NULL,
    `queueSize` = NULL,
    `count` = NULL,
    initialize = function(`indexing`, `queue`, `currentEntitySet`, `queueSize`, `count`){
      if (!missing(`indexing`)) {
                stopifnot(R6::is.R6(`indexing`))
        self$`indexing` <- `indexing`
      }
      if (!missing(`queue`)) {
                stopifnot(is.vector(`queue`), length(`queue`) != 0)
                sapply(`queue`, function(x) stopifnot(is.character(x)))
        self$`queue` <- `queue`
      }
      if (!missing(`currentEntitySet`)) {
                stopifnot(is.character(`currentEntitySet`), length(`currentEntitySet`) == 1)
        self$`currentEntitySet` <- `currentEntitySet`
      }
      if (!missing(`queueSize`)) {
                stopifnot(is.numeric(`queueSize`), length(`queueSize`) == 1)
        self$`queueSize` <- `queueSize`
      }
      if (!missing(`count`)) {
                stopifnot(is.numeric(`count`), length(`count`) == 1)
        self$`count` <- `count`
      }
    },
    toJSON = function() {
      IndexingStateObject <- list()
      if (!is.null(self$`indexing`)) {
        IndexingStateObject[['indexing']] <-
                self$`indexing`$toJSON()
      }
      if (!is.null(self$`queue`)) {
        IndexingStateObject[['queue']] <-
                self$`queue`
      }
      if (!is.null(self$`currentEntitySet`)) {
        IndexingStateObject[['currentEntitySet']] <-
                self$`currentEntitySet`
      }
      if (!is.null(self$`queueSize`)) {
        IndexingStateObject[['queueSize']] <-
                self$`queueSize`
      }
      if (!is.null(self$`count`)) {
        IndexingStateObject[['count']] <-
                self$`count`
      }

      IndexingStateObject
    },
    fromJSON = function(IndexingStateJson) {
      IndexingStateObject <- jsonlite::fromJSON(IndexingStateJson)
      if (!is.null(IndexingStateObject$`indexing`)) {
                indexingObject <- character$new()
                indexingObject$fromJSON(jsonlite::toJSON(IndexingStateObject$indexing, auto_unbox = TRUE))
                self$`indexing` <- indexingObject
      }
      if (!is.null(IndexingStateObject$`queue`)) {
                self$`queue` <- IndexingStateObject$`queue`
      }
      if (!is.null(IndexingStateObject$`currentEntitySet`)) {
                self$`currentEntitySet` <- IndexingStateObject$`currentEntitySet`
      }
      if (!is.null(IndexingStateObject$`queueSize`)) {
                self$`queueSize` <- IndexingStateObject$`queueSize`
      }
      if (!is.null(IndexingStateObject$`count`)) {
                self$`count` <- IndexingStateObject$`count`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "indexing":
                  "%s"
              ,
           "queue":
                      
                      ["%s"]
                  
              ,
           "currentEntitySet":
                      
                      "%s"
                  
              ,
           "queueSize":
                      %d
                      
                  
              ,
           "count":
                      %d
                      
                  
              
        }',
                self$`indexing`$toJSON(),
                paste0(self$`queue`, collapse='","'),
                self$`currentEntitySet`,
                self$`queueSize`,
                self$`count`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(IndexingStateJson) {
      IndexingStateObject <- jsonlite::fromJSON(IndexingStateJson)
              characterObject <- character$new()
              self$`indexing` <- characterObject$fromJSON(jsonlite::toJSON(IndexingStateObject$indexing, auto_unbox = TRUE))
              self$`queue` <- IndexingStateObject$`queue`
              self$`currentEntitySet` <- IndexingStateObject$`currentEntitySet`
              self$`queueSize` <- IndexingStateObject$`queueSize`
              self$`count` <- IndexingStateObject$`count`
    }
  )
)
