# OpenLattice API
#
# OpenLattice API
#
# The version of the OpenAPI document: 0.0.1
# Contact: support@openlattice.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SecurablePrincipal
#'
#' @description SecurablePrincipal Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field principal  \link{Principal} [optional]
#'
#' @field title  character [optional]
#'
#' @field description  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SecurablePrincipal <- R6::R6Class(
  'SecurablePrincipal',
  public = list(
    `id` = NULL,
    `principal` = NULL,
    `title` = NULL,
    `description` = NULL,
    initialize = function(
        `id`=NULL, `principal`=NULL, `title`=NULL, `description`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`principal`)) {
        stopifnot(R6::is.R6(`principal`))
        self$`principal` <- `principal`
      }
      if (!is.null(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      SecurablePrincipalObject <- list()
      if (!is.null(self$`id`)) {
        SecurablePrincipalObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`principal`)) {
        SecurablePrincipalObject[['principal']] <-
          self$`principal`$toJSON()
      }
      if (!is.null(self$`title`)) {
        SecurablePrincipalObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`description`)) {
        SecurablePrincipalObject[['description']] <-
          self$`description`
      }

      SecurablePrincipalObject
    },
    fromJSON = function(SecurablePrincipalJson) {
      SecurablePrincipalObject <- jsonlite::fromJSON(SecurablePrincipalJson)
      if (!is.null(SecurablePrincipalObject$`id`)) {
        self$`id` <- SecurablePrincipalObject$`id`
      }
      if (!is.null(SecurablePrincipalObject$`principal`)) {
        principalObject <- Principal$new()
        principalObject$fromJSON(jsonlite::toJSON(SecurablePrincipalObject$principal, auto_unbox = TRUE, digits = NA))
        self$`principal` <- principalObject
      }
      if (!is.null(SecurablePrincipalObject$`title`)) {
        self$`title` <- SecurablePrincipalObject$`title`
      }
      if (!is.null(SecurablePrincipalObject$`description`)) {
        self$`description` <- SecurablePrincipalObject$`description`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`principal`)) {
        sprintf(
        '"principal":
        %s
        ',
        jsonlite::toJSON(self$`principal`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SecurablePrincipalJson) {
      SecurablePrincipalObject <- jsonlite::fromJSON(SecurablePrincipalJson)
      self$`id` <- SecurablePrincipalObject$`id`
      self$`principal` <- Principal$new()$fromJSON(jsonlite::toJSON(SecurablePrincipalObject$principal, auto_unbox = TRUE, digits = NA))
      self$`title` <- SecurablePrincipalObject$`title`
      self$`description` <- SecurablePrincipalObject$`description`
      self
    }
  )
)

