# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LinkingApi")

api.instance <- LinkingApi$new()

test_that("AddLinkingFeedback", {
  # tests for AddLinkingFeedback
  # base path: https://api.openlattice.com
  # Submits feedbacks for a given linking entity set and linking id in a batch format.
  # @param LinkingFeedback  linking.feedback   
  # @return [integer]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteLinkingFeedback", {
  # tests for DeleteLinkingFeedback
  # base path: https://api.openlattice.com
  # Deletes linking feedback
  # @param EntityKeyPair  entity.key.pair   
  # @return [integer]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllLinkingFeedback", {
  # tests for GetAllLinkingFeedback
  # base path: https://api.openlattice.com
  # Returns all feedback submitted
  # @return [array[EntityLinkingFeedback]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllLinkingFeedbackWithFeatures", {
  # tests for GetAllLinkingFeedbackWithFeatures
  # base path: https://api.openlattice.com
  # Returns all feedback submitted walong with the features of pairwise entities
  # @return [array[EntityLinkingFeatures]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetLinkingFeedbackWithFeatures", {
  # tests for GetLinkingFeedbackWithFeatures
  # base path: https://api.openlattice.com
  # Returns the feedback on the given entity pair along with their features
  # @param EntityKeyPair  entity.key.pair   
  # @return [EntityLinkingFeatures]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetLinkingFeedbacksOnEntity", {
  # tests for GetLinkingFeedbacksOnEntity
  # base path: https://api.openlattice.com
  # Returns positive/negative/all linking feedbacks on the given entity.
  # @param character  feedback.type   
  # @param EntityDataKey  entity.data.key   
  # @return [array[EntityLinkingFeedback]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

