# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Acl")

model.instance <- Acl$new()

test_that("aclKey", {
  # tests for the property `aclKey` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`aclKey`, "EXPECTED_RESULT")
})

test_that("aces", {
  # tests for the property `aces` (array[Ace])

  # uncomment below to test the property 
  #expect_equal(model.instance$`aces`, "EXPECTED_RESULT")
})

