# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NeighborEntityDetails")

model.instance <- NeighborEntityDetails$new()

test_that("associationEntitySet", {
  # tests for the property `associationEntitySet` (EntitySet)

  # uncomment below to test the property 
  #expect_equal(model.instance$`associationEntitySet`, "EXPECTED_RESULT")
})

test_that("associationDetails", {
  # tests for the property `associationDetails` (map(array[character]))

  # uncomment below to test the property 
  #expect_equal(model.instance$`associationDetails`, "EXPECTED_RESULT")
})

test_that("neighborEntitySet", {
  # tests for the property `neighborEntitySet` (EntitySet)

  # uncomment below to test the property 
  #expect_equal(model.instance$`neighborEntitySet`, "EXPECTED_RESULT")
})

test_that("neighborId", {
  # tests for the property `neighborId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`neighborId`, "EXPECTED_RESULT")
})

test_that("neighborDetails", {
  # tests for the property `neighborDetails` (map(array[character]))

  # uncomment below to test the property 
  #expect_equal(model.instance$`neighborDetails`, "EXPECTED_RESULT")
})

