# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FilteredDataPageDefinition")

model.instance <- FilteredDataPageDefinition$new()

test_that("pageSize", {
  # tests for the property `pageSize` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pageSize`, "EXPECTED_RESULT")
})

test_that("bookmarkId", {
  # tests for the property `bookmarkId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`bookmarkId`, "EXPECTED_RESULT")
})

test_that("propertyTypeId", {
  # tests for the property `propertyTypeId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`propertyTypeId`, "EXPECTED_RESULT")
})

test_that("filter", {
  # tests for the property `filter` (list(Filter))

  # uncomment below to test the property 
  #expect_equal(model.instance$`filter`, "EXPECTED_RESULT")
})

