/**
 * OpenLattice API
 * OpenLattice API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Constraint from './Constraint';

/**
 * The ConstraintGroup model module.
 * @module model/ConstraintGroup
 * @version 0.0.1
 */
class ConstraintGroup {
    /**
     * Constructs a new <code>ConstraintGroup</code>.
     * @alias module:model/ConstraintGroup
     */
    constructor() { 
        
        ConstraintGroup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConstraintGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstraintGroup} obj Optional instance to populate.
     * @return {module:model/ConstraintGroup} The populated <code>ConstraintGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstraintGroup();

            if (data.hasOwnProperty('min')) {
                obj['min'] = ApiClient.convertToType(data['min'], 'Number');
            }
            if (data.hasOwnProperty('constraints')) {
                obj['constraints'] = ApiClient.convertToType(data['constraints'], [Constraint]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} min
 */
ConstraintGroup.prototype['min'] = undefined;

/**
 * @member {Array.<module:model/Constraint>} constraints
 */
ConstraintGroup.prototype['constraints'] = undefined;






export default ConstraintGroup;

