/**
 * OpenLattice API
 * OpenLattice API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityLinkingFeedback from './EntityLinkingFeedback';

/**
 * The EntityLinkingFeatures model module.
 * @module model/EntityLinkingFeatures
 * @version 0.0.1
 */
class EntityLinkingFeatures {
    /**
     * Constructs a new <code>EntityLinkingFeatures</code>.
     * @alias module:model/EntityLinkingFeatures
     */
    constructor() { 
        
        EntityLinkingFeatures.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityLinkingFeatures</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityLinkingFeatures} obj Optional instance to populate.
     * @return {module:model/EntityLinkingFeatures} The populated <code>EntityLinkingFeatures</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityLinkingFeatures();

            if (data.hasOwnProperty('entityLinkingFeedback')) {
                obj['entityLinkingFeedback'] = EntityLinkingFeedback.constructFromObject(data['entityLinkingFeedback']);
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = ApiClient.convertToType(data['features'], {'String': 'Number'});
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/EntityLinkingFeedback} entityLinkingFeedback
 */
EntityLinkingFeatures.prototype['entityLinkingFeedback'] = undefined;

/**
 * @member {Object.<String, Number>} features
 */
EntityLinkingFeatures.prototype['features'] = undefined;






export default EntityLinkingFeatures;

