/**
 * OpenLattice API
 * OpenLattice API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@openlattice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntitySet from './EntitySet';
import PropertyType from './PropertyType';

/**
 * The SearchResultHits model module.
 * @module model/SearchResultHits
 * @version 0.0.1
 */
class SearchResultHits {
    /**
     * Constructs a new <code>SearchResultHits</code>.
     * @alias module:model/SearchResultHits
     */
    constructor() { 
        
        SearchResultHits.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchResultHits</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchResultHits} obj Optional instance to populate.
     * @return {module:model/SearchResultHits} The populated <code>SearchResultHits</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchResultHits();

            if (data.hasOwnProperty('propertyTypes')) {
                obj['propertyTypes'] = ApiClient.convertToType(data['propertyTypes'], [PropertyType]);
            }
            if (data.hasOwnProperty('entitySet')) {
                obj['entitySet'] = EntitySet.constructFromObject(data['entitySet']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PropertyType>} propertyTypes
 */
SearchResultHits.prototype['propertyTypes'] = undefined;

/**
 * @member {module:model/EntitySet} entitySet
 */
SearchResultHits.prototype['entitySet'] = undefined;






export default SearchResultHits;

