/*
 * OpenLattice API
 *
 * OpenLattice API
 *
 * API version: 0.0.1
 * Contact: support@openlattice.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openlattice
// DataSetColumn struct for DataSetColumn
type DataSetColumn struct {
	Id string `json:"id,omitempty"`
	DataSetId string `json:"dataSetId,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizationId string `json:"organizationId,omitempty"`
	DataType string `json:"dataType,omitempty"`
	Metadata SecurableObjectMetadataUpdate `json:"metadata,omitempty"`
	AclKey []string `json:"aclKey,omitempty"`
}
