/*
 * OpenLattice API
 *
 * OpenLattice API
 *
 * API version: 0.0.1
 * Contact: support@openlattice.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openlattice
// EntityTypePropertyMetadata struct for EntityTypePropertyMetadata
type EntityTypePropertyMetadata struct {
	Title string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
}
